#/turtlesim:
#  ros__parameters:
#    background_b: 255
#    background_g: 255
#    background_r: 69
#   use_sim_time: false

/**:
   ros__parameters:
      background_b: 255
      background_g: 86
      background_r: 150